### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by ConanCui** [Jhy1993/HAN#1]
你好，想请问你的 load_data_dblp函数里，在导入ACM.mat数据时，找不到对应的 data['label'], data['feature']，请问是不是数据不对呢？

**Comment by Jhy1993** [comment]
那个是未经处理的  处理后的太大了 我传到百度网盘了 链接：https://pan.baidu.com/s/1V2iOikRqHPtVvaANdkzROw 
提取码：50k2 

 供你参考
