### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by XinyiZ001** [Jhy1993/HAN#10]
Hi,
Thanks for sharing your code.

Here I have a question related to the ACM data preprocessing.

When I extract papers from KDD, SIGMOD,SIGCOMM, MobiCOMM, and VLDB, there are ```4025``` papers which is different from what is reported in your paper. Could you pls tell me where the problem might be? Or can you share the cleaned data (not the PAP, PLP adjacency matrix)? 

Thanks!

**Comment by siri-ius** [comment]
Hi,

did you get an answer?

Thanks!

**Comment by shirinmous** [comment]
Hi 
there are 4025 papers from KDD, SIGMOD,SIGCOMM, MobiCOMM, and VLDB, but for having balanced classes they randomly select 994 papers from database class (SIGCOMM and MOBICOMM) from 1994 papers.
