### ISSUE TITLE
GCN和GAN上的实验如何做的？

### ISSUE THREAD

**Issue by yuanyuansiyuan** [Jhy1993/HAN#11]
1. 论文提出的方法通过meta-path找到邻居后，直接进行接下来的两层attention操作，而不是像GCN中节点embedding的扩散式表示？ 请问是否有试验过，在本文模型的基础上，对meta-path进行GCN操作，即对于中心节点，他的表示为自身 + meta-path上从邻居开始一层层传递过来的表示？
2. GCN和GAN的实验论文中描述为 在GCN上测试了所有的meta-path，然后取了最好的结果，请问具体是怎么做的？
是GCN传递的时候，对每个节点，不是所有邻居，只是多条meta-path传递过来的表示？从中取最好的结果是什么意思呢？
3. 本文没有用GCN中的表示传递，但能超过GCN, 说明靠meta-path找到的邻居已经包含了重要的信息？ 另外能超过GAN, 说明层级注意力机制比较有效？

**Comment by Jhy1993** [comment]
node-level是类似gcn的聚合，聚合meta-path based neighbors（including itsself）
GCN和GAT我们都是测试不同meta-path下的同质网络，然后汇报最好结果。
node-level attention类似gat可以实现较好的对邻居加权（见attention analysis）。
semantic-level可以多方面描述节点，信息更加全面，所以也更好。

**Comment by yuanyuansiyuan** [comment]
谢谢回答，补充问题
1.node-level 是类似gcn的聚合，但不会多层去传递对么，就是直接拿到邻居节点的表示
