### ISSUE TITLE
如何预处理ACM数据

### ISSUE THREAD

**Issue by anny0316** [Jhy1993/HAN#12]
非常感谢分享的代码，但是对于异构的网络（不同的节点、不同的边），如何预处理数据集？我的理解是需要把不同类型的节点映射到同一个特征空间，在本文中是如何处理的？请问方便公开一下清洗ACM 或者 DBLP4area数据集的清洗脚本，或者是能更详细说明一下论文里所用数据集是如何基于原始ACM 或者 dblp4area数据集清洗得来的吗？谢谢。

**Comment by Jhy1993** [comment]
我们抽取了原始数据集的子网络，同时对一些节点进行了过滤，如没有辨识度的term会被删除。
然后分别建立不同mp下的邻接矩阵 如A-*-A和P-*-P。
详细部分见load data

**Comment by anny0316** [comment]
请问在哪里可以找到 load data ？代码里好像没有啊
