### ISSUE TITLE
Questions about model

### ISSUE THREAD

**Issue by Ailing-Zou** [Jhy1993/HAN#13]
Hi, 
here I have one question about HAN:

1. (I have found your previous answer to this quesion) In your code, the dataset is named as "ACM3020.mat'' while it is "ACM.mat" in the file. I change the code's name to load the data, but it seems that they are different data. So which one is right?

2. Could you please tell me whether HAN can be applied to weighted and directed graph with attribute?

Look forward to your reply!

**Comment by Jhy1993** [comment]
ACM.mat is the original dataset, ACM3025.mat is the preprocessed dataset.
