### ISSUE TITLE
IMDB数据提取问题

### ISSUE THREAD

**Issue by SuyuanLiu** [Jhy1993/HAN#14]
你好，我在提取IMDB数据过程中遇到一些问题，希望能得到你的帮助。
- 我提取genres中有action,comedy,drama类别的movie，但是我只得到了4380个movie，与论文中不一致，请问你是怎么提取的呢？
- movie feature，我提取plot_keywords中单词（去掉短句/词组），得到了3185个单词，与论文中也不一致，请问你这边单词是怎么处理的呢，后续人为挑选单词吗？
- train，val，test的数量加和为什么与movie总数量不一致呢？

**Comment by Jhy1993** [comment]
这里是单分类，所以类别多于1个也过滤了。
后续手动去除了一些非停用词的词 比如x-man，同时也出出现频率过高和过低的keyword进行了过滤。
这里只选取了3种类型的电影，全部的电影类型不止3种。
