### ISSUE TITLE
关于DBLP数据集的问题

### ISSUE THREAD

**Issue by cynricfu** [Jhy1993/HAN#16]
在论文中有提到author的feature是bag-of-words represented keywords
请问author的keywords是从哪里提取的呢，这个repo里好像并未提供

**Comment by cynricfu** [comment]
DBLP4057_GAT_with_idx.mat 中有提供features，但还不清楚从哪里提取keywords的

**Comment by mengcao327** [comment]
我也有这个疑问，同求解答

**Comment by Jhy1993** [comment]
author发的所有的paper的关键词，作为author的feature。

**Comment by NicksonCheng** [comment]
那請問paper, conference, term的feature是怎麼做的?謝謝
