### ISSUE TITLE
Classification task enquiry

### ISSUE THREAD

**Issue by amblee0306** [Jhy1993/HAN#21]
taking the IMDB dataset for example, the paper mentioned using M-A-M and M-D-M metapaths to generate embeddings. To be specific, it only generated embeddings for the movie-typed nodes. Thus, may I ask how did you perform the node classification task? for instance, if I input a feature vector of an Actor instance, am I able to obtain the return that specify class A even when the model didn't learn to embed actor types?

**Comment by amblee0306** [comment]
misunderstood the task. figured it out.

**Comment by linz2000** [comment]
> 

Hello, I have the same confusion as you now, and could i know how you figured it out?
