### ISSUE TITLE
关于如何处理IMDB数据集

### ISSUE THREAD

**Issue by kepsail** [Jhy1993/HAN#3]
您好，IMDB数据集中，电影的类型可能有多个(multi label)对吗？请问是如何处理的？

另外代码缺失了一个实验脚本 jhyexps.py

**Comment by Jhy1993** [comment]
对的，这里每个电影只抽取其中一个label来作为新的label。
你再取出embedding之后将x，y送入到sklearn中的KMean或者KNN即可。
