### ISSUE TITLE
从来没见过如此糟糕的工作

### ISSUE THREAD

**Issue by xhcgit** [Jhy1993/HAN#31]
这是我见过最差劲的顶会论文的代码，写的乱七八糟，连本科生的水平都没有。不提供TensorFlow等版本要求，也不提供数据处理代码（preprocess_dblp.py我不知道是不是数据处理代码，但是无法运行），论文中也没有提及是根据什么策略获取到meta-path
preprocess_dblp.py（根本无法运行，一堆未定义的变量，我不知道你为什么要公布这样的代码）
ex_acm3025.py（这个代码写的也是一塌糊涂）
我不知道这位纪厚业同学的代码水平为何如此糟糕。

**Comment by Yanglazi** [comment]
这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的

**Comment by xhcgit** [comment]
> 
> 
> 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的

那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。

**Comment by xhcgit** [comment]
> 
> 
> 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的



> 
> 
> 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的

**Comment by Yanglazi** [comment]
https://github.com/dmlc/dgl/tree/master/examples/pytorch/han&nbsp;这里有一份pytorch的实现可以参考一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xhcgit"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 中午11:19
收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 
抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31)





 
Closed #31.

**Comment by xhcgit** [comment]
> 
> [https://github.com/dmlc/dgl/tree/master/examples/pytorch/han&nbsp;这里有一份pytorch的实现可以参考一下](https://github.com/dmlc/dgl/tree/master/examples/pytorch/han&nbsp;%E8%BF%99%E9%87%8C%E6%9C%89%E4%B8%80%E4%BB%BDpytorch%E7%9A%84%E5%AE%9E%E7%8E%B0%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xhcgit"<notifications@github.com&gt;; 发送时间: 2020年3月26日(星期四) 中午11:19 收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31) Closed #31. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢万分

**Comment by Jhy1993** [comment]
> 这是我见过最差劲的顶会论文的代码，写的乱七八糟，连本科生的水平都没有。不提供TensorFlow等版本要求，也不提供数据处理代码（preprocess_dblp.py我不知道是不是数据处理代码，但是无法运行），论文中也没有提及是根据什么策略获取到meta-path
> preprocess_dblp.py（根本无法运行，一堆未定义的变量，我不知道你为什么要公布这样的代码）
> ex_acm3025.py（这个代码写的也是一塌糊涂）
> 我不知道这位纪厚业同学的代码水平为何如此糟糕。

这份代码是基于GAT的实现, 本质相当于多个GAT的组合. DGL的实现也是这个思路. 如果你看不懂的,应该先去喷GAT作者的代码.

**Comment by Jhy1993** [comment]
> 这是我见过最差劲的顶会论文的代码，写的乱七八糟，连本科生的水平都没有。不提供TensorFlow等版本要求，也不提供数据处理代码（preprocess_dblp.py我不知道是不是数据处理代码，但是无法运行），论文中也没有提及是根据什么策略获取到meta-path
> preprocess_dblp.py（根本无法运行，一堆未定义的变量，我不知道你为什么要公布这样的代码）
> ex_acm3025.py（这个代码写的也是一塌糊涂）
> 我不知道这位纪厚业同学的代码水平为何如此糟糕。

预处理的代码也是应某些人的要求,放出的处理思路. 仅供参考.

**Comment by Jhy1993** [comment]
> > 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的
> 
> 那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。

我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码.

**Comment by Yanglazi** [comment]
请教一下作者，HAN其实还是一个同质网络是吧，只能embedding同质节点，请问作者对像metapath2vec这样能同时embedding整个异构网络方面的工作有过研究吗，我看作者在实验结果上metapath2vec的效果不太好，在这方面的工作有比较新的进展吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Houye"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 中午1:08
收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 
抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31)





   
这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的
  
那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。
  
我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码.

**Comment by xhcgit** [comment]
> 
> 
> > > 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的
> > 
> > 
> > 那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。
> 
> 我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码.

我认为作为一篇WWW文章的作者，你应该好好重写一下自己的实验代码(ex_acm3025.py)，还有请规范一下你的代码文件名（jhyexps.py你的起名也是让人无法理解，这是一篇有众多作者的论文，不是你的课程大作业）。还有起码放出从原始数据到获取meta-path，到最后构建训练数据的整个数据处理的代码，而不是放出preprocess_dblp这种根本无法运行也无法让人理解的数据处理代码和ACM.mat这种无法使用的数据（或许提供原始数据+数据处理代码会是一个更好的选择）。
我不知道我是不是看漏了，在HAN的论文中没有提及如何获取meta-path，还是像你们另外一篇在TKDE的文章提到的方法？包括我下载好的ACM数据集也是莫名其妙的，也请按照论文中提到PAP、PSP两条meta-path去构建训练数据，而不是莫名其妙出现三条meta-path（“PAP”,"PTP","PLP"）。还有就是你针对不同数据集都使用不同测试文件，也请提供另外两个数据集的实验代码。而不是在acm测试文件中起一个这样的load_data_dblp函数名（或许load_data_acm更好）。
一篇顶会的论文不仅仅是文章写的好，也希望整个项目的代码是易于理解和能够直接运行并能够复现的。
最后我为我激烈的言辞道歉，因为我最近频繁的被别人的代码影响了心情，并影响了我的论文进度。还有你们这篇论文确实写得挺好的，唯一的不足是好像并没有提到如何获取meta-path based neighbors。

**Comment by Yanglazi** [comment]
如果弄明白了PAP矩阵是如何生成的可否告知一下，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xhcgit"<notifications@github.com&gt;; 
发送时间: 2020年3月26日(星期四) 下午2:18
收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 
抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31)





    
这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的
  
那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。
  
我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码.
  
我认为作为一篇WWW文章的作者，你应该好好重写一下自己的实验代码(ex_acm3025.py)，还有请规范一下你的代码文件名（jhyexps.py你的起名也是让人无法理解，这是一篇有众多作者的论文，不是你的课程大作业）。还有起码放出从原始数据到获取meta-path，到最后构建训练数据的整个数据处理的代码，而不是放出preprocess_dblp这种根本无法运行也无法让人理解的数据处理代码和ACM.mat这种无法使用的数据（或许提供原始数据+数据处理代码会是一个更好的选择）。
 我不知道我是不是看漏了，在HAN的论文中没有提及如何获取meta-path，还是像你们另外一篇在TKDE的文章提到的方法？包括我下载好的ACM数据集也是莫名其妙的，也请按照论文中提到PAP、PSP两条meta-path去构建训练数据，而不是莫名其妙出现三条meta-path（“PAP”,"PTP","PLP"）。还有就是你针对不同数据集都使用不同测试文件，也请提供另外两个数据集的实验代码。而不是在acm测试文件中起一个这样的load_data_dblp函数名（或许load_data_acm更好）。
 一篇顶会的论文不仅仅是文章写的好，也希望整个项目的代码是易于理解和能够直接运行并能够复现的。
 最后我为我激烈的言辞道歉，因为我最近频繁的被别人的代码影响了心情，并影响了我的论文进度。还有你们这篇论文确实写得挺好的。

**Comment by jimmy-walker** [comment]
> > > 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的
> > 
> > 
> > 那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。
> 
> 我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码.

你好，作者。感谢你的工作。请问你的代码解析有发表了吗。没在你的知乎主页看到？

**Comment by Huangbuffer** [comment]
> 如果弄明白了PAP矩阵是如何生成的可否告知一下，非常感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xhcgit"<notifications@github.com&gt;; 发送时间: 2020年3月26日(星期四) 下午2:18 收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31) 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的 那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。 我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码. 我认为作为一篇WWW文章的作者，你应该好好重写一下自己的实验代码(ex_acm3025.py)，还有请规范一下你的代码文件名（jhyexps.py你的起名也是让人无法理解，这是一篇有众多作者的论文，不是你的课程大作业）。还有起码放出从原始数据到获取meta-path，到最后构建训练数据的整个数据处理的代码，而不是放出preprocess_dblp这种根本无法运行也无法让人理解的数据处理代码和ACM.mat这种无法使用的数据（或许提供原始数据+数据处理代码会是一个更好的选择）。 我不知道我是不是看漏了，在HAN的论文中没有提及如何获取meta-path，还是像你们另外一篇在TKDE的文章提到的方法？包括我下载好的ACM数据集也是莫名其妙的，也请按照论文中提到PAP、PSP两条meta-path去构建训练数据，而不是莫名其妙出现三条meta-path（“PAP”,"PTP","PLP"）。还有就是你针对不同数据集都使用不同测试文件，也请提供另外两个数据集的实验代码。而不是在acm测试文件中起一个这样的load_data_dblp函数名（或许load_data_acm更好）。 一篇顶会的论文不仅仅是文章写的好，也希望整个项目的代码是易于理解和能够直接运行并能够复现的。 最后我为我激烈的言辞道歉，因为我最近频繁的被别人的代码影响了心情，并影响了我的论文进度。还有你们这篇论文确实写得挺好的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

手动生产的，自己选几个meta-path就行

**Comment by jiangmeng12** [comment]
> [https://github.com/dmlc/dgl/tree/master/examples/pytorch/han&nbsp;这里有一份pytorch的实现可以参考一下](https://github.com/dmlc/dgl/tree/master/examples/pytorch/han&nbsp;%E8%BF%99%E9%87%8C%E6%9C%89%E4%B8%80%E4%BB%BDpytorch%E7%9A%84%E5%AE%9E%E7%8E%B0%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xhcgit"<notifications@github.com&gt;; 发送时间: 2020年3月26日(星期四) 中午11:19 收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31) Closed #31. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问还有关于这个的代码吗，您之前发的这个看不了

**Comment by jiangmeng12** [comment]
> > 如果弄明白了PAP矩阵是如何生成的可否告知一下，非常感谢
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "xhcgit"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年3月26日(星期四) 下午2:18 收件人: "Jhy1993/HAN"<[HAN@noreply.github.com](mailto:HAN@noreply.github.com)>; 抄送: "1054487156"<[1054487156@qq.com](mailto:1054487156@qq.com)>; "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31) 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的 那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。 我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码. 我认为作为一篇WWW文章的作者，你应该好好重写一下自己的实验代码(ex_acm3025.py)，还有请规范一下你的代码文件名（jhyexps.py你的起名也是让人无法理解，这是一篇有众多作者的论文，不是你的课程大作业）。还有起码放出从原始数据到获取meta-path，到最后构建训练数据的整个数据处理的代码，而不是放出preprocess_dblp这种根本无法运行也无法让人理解的数据处理代码和ACM.mat这种无法使用的数据（或许提供原始数据+数据处理代码会是一个更好的选择）。 我不知道我是不是看漏了，在HAN的论文中没有提及如何获取meta-path，还是像你们另外一篇在TKDE的文章提到的方法？包括我下载好的ACM数据集也是莫名其妙的，也请按照论文中提到PAP、PSP两条meta-path去构建训练数据，而不是莫名其妙出现三条meta-path（“PAP”,"PTP","PLP"）。还有就是你针对不同数据集都使用不同测试文件，也请提供另外两个数据集的实验代码。而不是在acm测试文件中起一个这样的load_data_dblp函数名（或许load_data_acm更好）。 一篇顶会的论文不仅仅是文章写的好，也希望整个项目的代码是易于理解和能够直接运行并能够复现的。 最后我为我激烈的言辞道歉，因为我最近频繁的被别人的代码影响了心情，并影响了我的论文进度。还有你们这篇论文确实写得挺好的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 手动生产的，自己选几个meta-path就行

想问您一下，你最终用的是jhy的代码吗

**Comment by jiangmeng12** [comment]
> 如果弄明白了PAP矩阵是如何生成的可否告知一下，非常感谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xhcgit"<notifications@github.com&gt;; 发送时间: 2020年3月26日(星期四) 下午2:18 收件人: "Jhy1993/HAN"<HAN@noreply.github.com&gt;; 抄送: "1054487156"<1054487156@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [Jhy1993/HAN] 从来没见过如此糟糕的工作 (#31) 这位兄弟有点过了，作者代码写的不怎么样，但是论文确实写的挺好的，这个工作本身还是挺有价值的 那代码写的能叫不怎么样？简直是在耽误大家的工作。也不提供数据处理代码，preprocess_dblp.py这种根本无法运行的文件发出来的意义是什么。 我近期会写一个代码解析放到我的知乎主页,希望有助于你理解代码. 我认为作为一篇WWW文章的作者，你应该好好重写一下自己的实验代码(ex_acm3025.py)，还有请规范一下你的代码文件名（jhyexps.py你的起名也是让人无法理解，这是一篇有众多作者的论文，不是你的课程大作业）。还有起码放出从原始数据到获取meta-path，到最后构建训练数据的整个数据处理的代码，而不是放出preprocess_dblp这种根本无法运行也无法让人理解的数据处理代码和ACM.mat这种无法使用的数据（或许提供原始数据+数据处理代码会是一个更好的选择）。 我不知道我是不是看漏了，在HAN的论文中没有提及如何获取meta-path，还是像你们另外一篇在TKDE的文章提到的方法？包括我下载好的ACM数据集也是莫名其妙的，也请按照论文中提到PAP、PSP两条meta-path去构建训练数据，而不是莫名其妙出现三条meta-path（“PAP”,"PTP","PLP"）。还有就是你针对不同数据集都使用不同测试文件，也请提供另外两个数据集的实验代码。而不是在acm测试文件中起一个这样的load_data_dblp函数名（或许load_data_acm更好）。 一篇顶会的论文不仅仅是文章写的好，也希望整个项目的代码是易于理解和能够直接运行并能够复现的。 最后我为我激烈的言辞道歉，因为我最近频繁的被别人的代码影响了心情，并影响了我的论文进度。还有你们这篇论文确实写得挺好的。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

请问您知道是怎么产生的了吗

**Comment by chenyan404** [comment]
> 

同求
