### ISSUE TITLE
最后利用KNN进行分类的实验设置是否合理？

### ISSUE THREAD

**Issue by kepsail** [Jhy1993/HAN#4]
ex_acm3025.py 脚本中，最终用test_mask选出的特征和标签训练KNN进行分类，这样做的意义是：在测试集上划分了训练集、测试集，这样设置是不合理的。为了公平地和其他方法进行比较，应该用所有的特征，以及train_mask选出的标签训练KNN，然后测试KNN在test_mask上的分类效果。

**Comment by Jhy1993** [comment]
我们没有像GCN和GAT那样只关注半监督分类的准确性。这里最终的目的是对所学习到的表示进行评估，即：将所有test节点的表示及标签取出来进行评测。 这里为了保证公平，所有算法取出来的都是相同节点的表示。然后套用现有Network Embedding中的Embedding测评方法来评估。
