### ISSUE TITLE
imdb的输入特征矩阵

### ISSUE THREAD

**Issue by TCcoder** [Jhy1993/HAN#8]
您好！请问IMDB的数据集的输入矩阵是怎样的？我用了论文中M-A-M（电影-演员-电影）来分类电影类型，以每部电影为结点，该节点的特征向量用演员one-hot，是一个非常稀疏的矩阵，而且，最后效果并不好，是我的特征矩阵错了吗？期待您的回复。。。

**Comment by Jhy1993** [comment]
用错了，具体见论文数据集描述

**Comment by TCcoder** [comment]
好的！问题已解决，非常感谢！
