### ISSUE TITLE
请问清洗DBLP4area数据集的更多细节

### ISSUE THREAD

**Issue by kepsail** [Jhy1993/HAN#9]
请问方便公开一下清洗DBLP4area数据集的清洗脚本，或者是能更详细说明一下论文里所用数据集是如何基于原始dblp4area数据集清洗得来的吗？谢谢。

我根据论文描述以如下方法在原始DBLP4area上清洗出来的数据集无法复现论文里报告的精度。
1. 选出带标签的A类型节点共4057个；
2. 选出和A类型节点有关联的P类型节点共14328个；
3. 选出和P类型有关联的C类型节点共20个，选出和P类型有关联的T类型节点共8898个（这里和论文里面的8789个略有差别）；
4.然后基于以上构造的邻接矩阵，对于某条metapath，用该路径下对应的邻接矩阵的序列的点积来求该路径的commuting matrix；

**Comment by smallhaes** [comment]
同楼上，感谢～

**Comment by Jhy1993** [comment]
我们的处理方法与这篇一致，供你参考。
HAHE: Hierarchical Aentive Heterogeneous Information Network Embedding
